# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47e880741b18e01b3f6fcb349a11af3dec69684eeb57072193b570633f01999d8ffe4374d4ffb5413cb5a67814aa402feaf1a659a1843c434f505f83f31b4359

test:
  secret_key_base: 3291239fccbe0e71899059fe06ece4aefae1c97f4065b9c11e621b8c152d065c6e5501445ab29327c672ac6eb687511f6624eca55520e560a88eafb80698df18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
